### ISSUE TITLE
Kickoff meeting on telemetry development 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/yarp-telemetry#1]
Hi everyone, I scheduled a meeting on Monday 2020/11/16 at 3 PM CET to kickoff the activities on the development of this libraries, mainly to clarify the objectives and users stories we want to address to @AlexAntn @Nicogene . 

People invited: 
@AlexAntn 
@Nicogene 
@S-Dafarra 
@vtikha  
@traversaro 
 
(If any of you want to reschedule for any reason, please let me know, thanks!) 

@drdanz if you like, feel free to join, thanks! 

cc @pattacini @DanielePucci @lornat75 @maggia80

**Comment by pattacini** [comment]
Thanks @traversaro 

Could you please forward the invitation anyway?
I'll try to join, at least at the beginning, if possible.

**Comment by traversaro** [comment]
Done!

**Comment by traversaro** [comment]
Weekly meetings have been scheduled, and for all the planned activities we opened issues in this repo.
