### ISSUE TITLE
telemetryDeviceDumper: add documentation

### ISSUE THREAD

**Issue by Nicogene** [robotology-playground/yarp-telemetry#101]
We should add Doxygen documentation with a table of the parameters and some example of configuration files

**Comment by Nicogene** [comment]
#106 partially fixes this, it add the doc in the readme, the Doxygen part is still missing.

**Comment by traversaro** [comment]
> 
> 
> #106 partially fixes this, it add the doc in the readme, the Doxygen part is still missing.

I think that the README is what most users will look at to use the device, so I think we can close this issue, and eventually we can open a new one to track further improvements.

**Comment by Nicogene** [comment]
Fixed by #106
