### ISSUE TITLE
yarp-device-dumper: Proposal for a YARP device-based logger to run in yarprobotinterface

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/yarp-telemetry#15]
**Note: this is not meant to be a replacement for full telemetry, but a small prototype can be easily implemented in a short range of time 
to achieve the goal of having a dumper always running to help debug of failures.**

# `yarp-device-dumper`

Similar to how the `yarpdatadumper` is a process used to connect to a YARP port and save the data on a file,
the `yarp-device-dumper` is a YARP device that is meant to run as part of a `yarprobotinterface` instance,
that runs a periodic thread that read data from a series of YARP devices passed via the `attach` action of the  `yarprobotinterface`.
For each thread run, the data is added in a [circular buffer](https://en.wikipedia.org/wiki/Circular_buffer), so that the 
device can always run without the risk of filling the `icub-head` PC memory. The size of the circular buffer can be 
configured to keep in memory only the desired last X minutes of experiments, to have a tradeoff between the data that 
can be saved and the use of memory. 

Once the yarprobotinterface is closed, or a write to file is requested in another way (such as a periodic save or a a RPC call), the 
data from the circular buffer is dumped to a `.mat` file on disk. 

By design, the data that is possible to collect will be configurable, but not arbitrary: the data can be collected only if the device 
expose them in properly supported YARP interfaces. For a first prototype, I guess it will be important to support control board interfaces,
such as [`ITorqueControl`](https://www.yarp.it/classyarp_1_1dev_1_1ITorqueControl.html) or [`IPositionControl`](https://www.yarp.it/classyarp_1_1dev_1_1IPositionControl.html).
For a second iteration, supporting also the data published on Multiple Analog Sensors interface. 

Main advantages over the existing pattern of having multiple yarpdatadumpers for all the ports that needs to be saved:
* No need to start manually the dumper: the dumper starts automatically as soon as you start the robot.
* No need to worry about clock time the data: data from different robot parts or from different sensors
  is implicitly synchronized by the fact that are read at the same time.
* No need to parse and merge multiple textual files: the data is already in a `.mat` file, 
  ready for plotting/post processing in MATLAB/Python/Julia/C++. 
* No need to worry about disconnection between the icub-head PC and the laptop on which yarpdatadumper
  are running (useful for when the iCub is running on Wi-Fi).
* No need to explicitly enable it: thanks to the use of the circular buffer, the dumper can just run always,
  and it will not access the disk unless at the hand of the experient, and it will not fill the icub-head RAM.

Limitations w.r.t. to the use of yarpdatadumpers:
* No images
* No data from external modules
* No arbitrary data

However, the yarp-device-dumper can also be used together with external yarpdatadumpers.

Possible dependencies: 
* YARP for the the device interfaces 
* matioCpp for saving data to .mat files
* For circular buffers, Boost.Circular Buffer https://www.boost.org/doc/libs/1_70_0/doc/html/circular_buffer.html 
  or just a custom class, based for example on https://gist.github.com/edwintcloud/d547a4f9ccaf7245b06f0e8782acefaa 
  
Similar approaches:
* https://github.com/ADVRHumanoids/MatLogger2

**Comment by Nicogene** [comment]
#84 implemented a first working draft of this proposal
