### ISSUE TITLE
Investigation file-based configuration of the buffer manager 

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/yarp-telemetry#39]

**Comment by Nicogene** [comment]
I found a very nice c++ library for parsing JSON files https://github.com/nlohmann/json

In particular, it can be imported also as a single header(see https://github.com/nlohmann/json/tree/develop/single_include/nlohmann) and in particular [this feature](https://github.com/nlohmann/json#arbitrary-types-conversions) is awesome.

We may implement the `from_json` and `to_json` in our `BufferConfig` struct!

cc @traversaro @AlexAntn @S-Dafarra

**Comment by traversaro** [comment]
Good idea! I would however implement it in separate function/headers, so that we can easily add more conversions in the future, for example from/to yarp::os::Property as well, and permit to users to provide their own conversions, as adding more functions is easy, while adding methods to an existing class is impossible outside of the project.

cc @GiulioRomualdi

**Comment by traversaro** [comment]
Regarding the use of single header, we can also support using like that (especially if we want to support 18.04 that has an old version: https://repology.org/project/nlohmann-json/versions), but I would have at least an option to find it externally via `find_package(nlohmann_json)`.

**Comment by Nicogene** [comment]
In #65 we implemented the configuration from json, and that library is really easy to use!
For what we understood the default behaviour is that all the fields have to be specified in the .json file, no one is taken as optional

We have to investigate how to handle the case in which the user forgot a parameter

**Comment by S-Dafarra** [comment]
It would be nice to have keywords like ``all`` to store all the parameters, or ``not`` to put some specific parameter in the blacklist.

**Comment by barbalberto** [comment]
I like that library as well, has a modern approach to C++.
The header only version is handy, except when you start using all over your
coffee it slows down compilation time.

Also uses a lot of exceptions whenever anything is not perfect, which
personally I don't like so much.

Also, the boost::ptree is a good alternative to parse json file

Il mar 9 feb 2021, 12:30 Nicolò Genesio (二コゲネ) <notifications@github.com>
ha scritto:

**Comment by Nicogene** [comment]
> Also uses a lot of exceptions whenever anything is not perfect, which
personally I don't like so much.

Me neither, when the file misses some attribute is not clear what is missing or what it is wrong
