### ISSUE TITLE
Prepare a simple example to save a vector and a matrix with matio-cpp

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/yarp-telemetry#4]

**Comment by S-Dafarra** [comment]
This is a first example of usage (beside the ones in the README or in the tests): https://github.com/dic-iit/bipedal-locomotion-framework/blob/535fe059fe555cda964f9db83eac269578b43121/utilities/MasImuTest/src/MasImuTest.cpp#L1141-L1167

The output file contains a struct named ``settings`` that is as follows
![image](https://user-images.githubusercontent.com/18591940/99264531-e0c4f200-2820-11eb-9ade-43e662080f2f.png)

In the same file, I also save a ``StructArray`` to store the information of several info I saved from the robot: 
https://github.com/dic-iit/bipedal-locomotion-framework/blob/535fe059fe555cda964f9db83eac269578b43121/utilities/MasImuTest/src/MasImuTest.cpp#L763-L883

The output is like
![image](https://user-images.githubusercontent.com/18591940/99264733-22ee3380-2821-11eb-9a9c-7eec4b67de16.png)

**Comment by traversaro** [comment]
If we want to also do a bit more advanced case, we can also look into saving a struct with this format on matio: https://github.com/robotology-playground/yarp-telemetry/issues/8 .

**Comment by AlexAntn** [comment]
> If we want to also do a bit more advanced case, we can also look into saving a struct with this format on matio: #8 .

I think it makes more sense, considering that @S-Dafarra already provided examples on how to write both a vector and matrix. I tested a minimal example (using the instructions provided on the dic/matio-cpp github page) and everything compiled and ran smoothly, and the installation of the library was fairly easy and fast.
