### ISSUE TITLE
Add unit test in the CI

### ISSUE THREAD

**Issue by Nicogene** [robotology-playground/yarp-telemetry#54]
We are in a stage where the API change often so it is difficult to implement and maintain unit tests, but at some point, we should introduce unit tests in the CI.

My proposal is to use [Catch2](https://github.com/catchorg/Catch2)

**Comment by GiulioRomualdi** [comment]
An example of usage:

- `Cmake` https://github.com/dic-iit/bipedal-locomotion-framework/blob/master/cmake/Catch2Main.cpp.in and  https://github.com/dic-iit/bipedal-locomotion-framework/blob/master/cmake/AddBipedalLocomotionUnitTest.cmake
- `cpp`: https://github.com/dic-iit/bipedal-locomotion-framework/blob/master/src/ParametersHandler/tests/ParametersHandlerTest.cpp

**Comment by traversaro** [comment]
To avoid regression such as https://github.com/robotology-playground/yarp-telemetry/issues/59, a low effort modification is also to run examples as tests, just to ensure that they run fine and eventually run them under valgrind to check if they don't memory errors.
