### ISSUE TITLE
Understand how to ensure mutual exclusion of the buffer

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/yarp-telemetry#9]

**Comment by traversaro** [comment]
This starts to be a problem given https://github.com/robotology-playground/yarp-telemetry/pull/55/files that creates a thread that is accessing the buffer on the top of the thread that is logging the data. Mutual access needs to be added, understanting what boost::circular_buffer is doing w.r.t. to that inside, and then understanding a proper stategy to add eventual mutual access.

**Comment by AlexAntn** [comment]
Checking the documentation on the circular buffer, it seems that reading is thread safe, but not writing. As such, we should take care to lock and unlock the buffer when there is such an access.

**Comment by traversaro** [comment]
Possible ideas:
* Check what yarpdatadumper does 
* To speed up the buffer save to file and minimize the time spent in locking the buffer, we could think of copying the buffer in a different buffer that then is saved to file

**Comment by Nicogene** [comment]
Not sure if this is related to the mutual exclusion, but the unit tests seem to fail in a non-deterministic way under macOs.
See https://github.com/robotology-playground/yarp-telemetry/runs/1989172341?check_suite_focus=true

**Comment by Nicogene** [comment]
Somehow related also to #94

**Comment by Nicogene** [comment]
Probably we have to lock the push_back calls (see https://github.com/robotology-playground/yarp-telemetry/pull/93#issuecomment-797651989), but maybe we can reduce the lock in the save(i.e. unlock as soon as we copied the data to save)

**Comment by Nicogene** [comment]
From https://github.com/robotology-playground/yarp-telemetry/issues/87#issuecomment-800918428 it is clear how the not correct mutual exclusion lead to or incorrect number of sample or dumping garbage(4 samples over 11k)
