### ISSUE TITLE
Make the fetchcontent verbose

### ISSUE THREAD

**Issue by Nicogene** [robotology-playground/yarp-telemetry#92]
When you configure the first time and you don't use the system `nhlomann_json`, the cmake seems stuck, but actually, it is pulling and compiling the library.

Feedback may be useful for the users that don't know we are using fetchContent

**Comment by Nicogene** [comment]
This issue it is fixed by #96

**Comment by S-Dafarra** [comment]
I swear I did not see this issue :joy:
